### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChrisAHolland**
Salutations.

I bring to you this pull request in the Year of our Lord 2020 to fix all know problems with your particular repository.

As your repository now has two contributors, I request a 50% stake in all profits made, else I will be retracting this valuable piece if code, thus corrupting all bits that comprise of your codebase.

Merge wisely.

### CODE REVIEW

**Comment by ChrisAHolland** [comment]
Still waiting...
homer

**Comment by mkitzan** [comment]
50% :eyes::sweat_drops: that's a big ask, but this is a pretty heavy +1/-1 commit. No way I could have arrived at this genius change...

Fool, 50% of $0 is $0. Let [Stallman's light shine](https://stallman.org/photos/rms-working/) on your greedy soul! You can begin repentance by [installing OpenBSD](https://www.openbsd.org/faq/faq4.html) from floppy disk or CD ROM. You may purchase the latest release [here](https://www.ebay.com/itm/OpenBSD-6-6-Install-Disk-More-Secure-Than-Linux/352987231666?hash=item522fadb5b2:g:4MwAAOSwaYpdgISW).

Thanks for the patch bud :ok_hand:

**Comment by ChrisAHolland** [comment]
Stallman's light has been eclipsed by the head of Steve Ballmer. The darkness provides me a realm to formulate complex algorithms as I have demonstrated in this particular pull request.

A good day to you, sir.

**Comment by mkitzan** [comment]
ballmer

**Pull request merged**
